config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :attendances
    resources :events
    resources :user_events

    root to: 'users#index'
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HighVoltage
  get '/dashboard' => 'dashboards#index', id: 'dashboard'
  get '/pages/user_manual' => 'pages#user_manual'

  resources :users, only: %i(edit update)
  resources :events, only: %i(new create show edit update destroy) do
    resources :attendances, only: %i(create index destroy) do
      collection do
        get 'export'
      end
    end
    resources :user_events, only: %i(create destroy)
  end
  resources :lookups, only: %i(index create)

  get '/heartbeat' => 'heartbeat#show'
  get '/heartbeat/api' => 'heartbeat#api'

  root to: 'pages#home', id: 'home'
end

app/models/event.rb
# frozen_string_literal: true

# Class for Cardswipr events
# @attr Title [String] Title of the event being made.
# @attr Description [String] Describes the event being made
class Event < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }

  before_validation :remove_whitespaces

  # Associations
  has_many :attendances, dependent: :destroy
  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events

  private

  def remove_whitespaces
    title.strip! if title.present?
    description.strip! if description.present?
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions
    # to implement custom behavior.
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Events Controller
class EventsController < ApplicationController
  prepend_before_action :set_event, only: %i(show edit update destroy)
  before_action :set_user_events, only: %i(edit update)
  layout 'application_without_nav_or_footer', only: %i(show)

  def new
    @event = Event.new
  end

  def create
    obj = EventCreator.new(params: event_params, owner: current_user)
    if obj.call
      redirect_to dashboard_path, notice: 'Successfully created event!'
    else
      @event = obj.event
      flash_alerts(obj)
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to edit_event_path(@event.id), notice: 'Event Updated'
    else
      flash_alerts(@event)
      render 'edit', event: @event.id
    end
  end

  def destroy
    @event.destroy
    redirect_to dashboard_path
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_user_events
    @user_event = UserEvent.new
    @user_events = @event.user_events
                         .joins(:user).order(Arel.sql('lower(last_name)'))
  end

  def event_params
    params.require(:event).permit(:title, :description)
  end

  def authorize!
    if @event
      authorize(@event)
    else
      authorize Event.new
    end
  end
end

app/views/events/_form.html.erb
<div class = "col-md-10">
  <%= simple_form_for @event do |f| %>
    <%= f.label 'Title'%>
    <%= f.input :title, label: false, error: '', input_html: { class: 'form-control' }%>
    <p><small>This will be displayed on the swipe-in screen in large text.</small></p> 
    <%= f.label 'Description'%>
    <%= f.input :description, label: false, error: '', input_html: { class: 'form-control' }%>
    <p><small>This will be displayed on the swipe-in screen in smaller text. You might tell attendees how you will use their email/netid, or what they should do after swiping in.</small></p>
    <%= f.submit class: "btn btn-yale"%>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class = "text-center">
  <h1>Edit Event: <%= @event.title %></h1>
</div>

<div class = "container">
  <%= render 'events/form' %>
  <br/>
  <div id='user-event-form'>
    <h3>Event Organizers</h3>
      <div class="container">
        <table aria-label="Event Organizers" class="event-organizers-table col-md-6">
          <thead>
            <tr>
              <th scope = "col">Name</th>
              <th scope = "col">NetId</th>
              <th scope = "col"></th>
            </tr>
          </thead>
          <tbody>
            <% @user_events.each do |user_event| %>
              <tr id= "remove-<%= user_event.user.username %>">
                <th scope = "row" data-role="Full Name"><%= user_event.user.full_name %></th>
                <td data-role = "NetId"><%= user_event.user.username %></td>
                <td data-role = "Remove Organizer">
                  <%= link_to 'X', event_user_event_path(user_event.event, user_event, user_event.id),
                  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger with-border", aria: { label: 'Remove Organizer' } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div>
          <%= form_tag event_user_events_path(@event, @user_event) do %>
            <%= text_field_tag :organizer, '', placeholder: 'NetID', :class => 'p-2' %>
            <%= submit_tag 'Add Organizer by NetID', :class => 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<br/>
<div class = "text-center">
  <h1>Create Event</h1>
</div>
<div class = "container">
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<%= button_to 'Back to Events', dashboard_path, method: :get, :class => 'btn btn-primary' %>
<br />
<div class="row">
  <div class="col-xl-6 offset-xl-3 col-lg-8 offset-lg-2 col-md-10 offset-md-1 col-12">
    <div class="container p-1">
    <%= render 'flashes' %>
    </div>
    <div class="card shadow text-center">
      <div class="card-header text-white bg-yale">
        <h2 class = "display-3"><b>Check in for <%=@event.title%></b></h2>
      </div>
      <div class="card-body">
        <p class="h3 m-1"><%=@event.description%></p>
        <br />
        <div class="h3 m-1">
          <p><b>Card Swipe</b> or <b>Card Tap</b> or <b>NetID</b></p>
        </div>
        <%= form_tag event_attendances_path(@event), id: 'swipr_swipe_form' do %>
          <div class="col-12 mx-auto input-group">
            <%= text_field_tag :search_param, '', autofocus: true, :class => 'p-2 form-control m-1' %>
            <%= submit_tag 'Check In', :class => 'btn btn-primary' %>
          </div>
        <% end %>
        <br />
        <p><%= @event.attendances.size %> Recorded</p>
      </div>
    </div>
  </div>
</div>