config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :attendances
    resources :events
    resources :user_events

    root to: 'users#index'
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HighVoltage
  get '/dashboard' => 'dashboards#index', id: 'dashboard'
  get '/pages/user_manual' => 'pages#user_manual'

  resources :users, only: %i(edit update)
  resources :events, only: %i(new create show edit update destroy) do
    resources :attendances, only: %i(create index destroy) do
      collection do
        get 'export'
      end
    end
    resources :user_events, only: %i(create destroy)
  end
  resources :lookups, only: %i(index create)

  get '/heartbeat' => 'heartbeat#show'
  get '/heartbeat/api' => 'heartbeat#api'

  root to: 'pages#home', id: 'home'
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  # Base administrate controller class.
  class ApplicationController < Administrate::ApplicationController
    include Pundit
    before_action :authorize!

    rescue_from Pundit::NotAuthorizedError do
      flash[:alert] = 'Sorry, you don\'t have permission to do that.'
      redirect_to(root_path)
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    private

    def authorize!
      if current_user
        authorize(current_user, :superuser_dash?)
      else
        authorize(User.new, :superuser_dash?)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base controller class.
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
  before_action :redirect_to_home_page, unless: :public_action?
  before_action :authorize!, unless: :public_action?

  rescue_from Pundit::NotAuthorizedError do
    flash[:alert] = 'Sorry, you don\'t have permission to do that.'
    redirect_to(root_path)
  end

  private

  def redirect_to_home_page
    return if user_signed_in?

    redirect_to root_path
    flash[:alert] = 'Please sign in to view that page'
  end

  def public_action?
    devise_controller? || self.class == HighVoltage::PagesController
  end

  def after_sign_in_path_for(user)
    if user.persisted?
      super user
    else
      person_attrs_to_user(user)
      user.save!
      user_session_path(user)
    end
  rescue StandardError
    flash[:alert] = 'We were unable to create your account. Please try later.'
    root_path
  end

  # to be used when rendering, not redirecting
  def flash_alerts(instance)
    instance.errors.full_messages.each do |message|
      flash.now[:alert] = message
    end
  end

  # retrieve and assign associated attributes from peoplehub to user
  def person_attrs_to_user(user)
    person = PeopleHub::PersonRequest.get(netid: user.username)
    user.email = person.email
    user.first_name = person.first_name
    user.last_name = person.last_name
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Base helper class.
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class='footer text-muted'>
  <ul class='footer-list'>
    <span>
      <li>Built by the <%= link_to 'Yale Student Developer and Mentorship Program', 'https://yalestc.github.io', target: '_blank' %></li>
    </span>
    <span class='right'>
      <li><%= link_to 'Accessibility at Yale', 'https://usability.yale.edu/web-accessibility/accessibility-yale', target: '_blank' %></li>
      <li>Contact the developers at <%= link_to 'app-dev@yale.edu', 'mailto:app-dev@yale.edu'%></li>
    </span>
  <ul>
</footer>

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light" aria-label="Main">
  <%= link_to "CardSwipr", root_path, method: :get, :class => 'navbar-brand text-decoration-none' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to dashboard_path, method: :get, :class => 'nav-link text-decoration-none', id: 'my_events_link' do %>
            <%= fa_icon 'calendar-alt', text: 'My Events' %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_event_path, method: :get, :class => 'nav-link text-decoration-none', id: 'new_event_link' do %>
            <%= fa_icon 'plus-square', text: 'Create New Event' %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to lookups_path, method: :get, :class => 'nav-link text-decoration-none', id: 'look_up_person_link' do %>
            <%= fa_icon 'id-card', text: 'Person Lookup' %>
          <% end %>
        </li>
        <% if policy(current_user).superuser_dash? %>
          <li class="nav-item">
            <%= link_to admin_users_path, method: :get, :class => 'nav-link text-decoration-none', id: 'admin_dashboard_link' do %>
              <%= fa_icon 'chart-area', text: 'Admin Dashboard' %>
            <% end %>
          </li>
        <% end %>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "#{current_user.first_name} #{current_user.last_name}", edit_user_path(current_user), method: :get, :class => "nav-link text-decoration-none" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => "nav-link text-decoration-none" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>