config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :attendances
    resources :events
    resources :user_events

    root to: 'users#index'
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HighVoltage
  get '/dashboard' => 'dashboards#index', id: 'dashboard'
  get '/pages/user_manual' => 'pages#user_manual'

  resources :users, only: %i(edit update)
  resources :events, only: %i(new create show edit update destroy) do
    resources :attendances, only: %i(create index destroy) do
      collection do
        get 'export'
      end
    end
    resources :user_events, only: %i(create destroy)
  end
  resources :lookups, only: %i(index create)

  get '/heartbeat' => 'heartbeat#show'
  get '/heartbeat/api' => 'heartbeat#api'

  root to: 'pages#home', id: 'home'
end

app/models/attendance.rb
# frozen_string_literal: true

# Model to represent Attendances
# @attr First_name [String] First name of the attendee
# @attr Last_name [String] Last name of the attendee
# @attr Email [String] Email of the attendee
# @attr Net_id [String] net id of the attendee
# @attr Upi [String] upi of the attendee
# @attr Phone [String] phone number of the attendee
# @attr Checked_in_at [DateTime] the date/time that the check in happens
class Attendance < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email,
            presence: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-\.]+[^.]\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false, scope: :event }
  validates :net_id, presence: true
  validates :upi, presence: true
  validates :checked_in_at, presence: true

  # Associations
  belongs_to :event
end

app/controllers/admin/attendances_controller.rb
# frozen_string_literal: true

module Admin
  class AttendancesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions
    # to implement custom behavior.
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

# controller for Attendance
class AttendancesController < ApplicationController
  prepend_before_action :set_event, only: %i(create index destroy export)

  def create
    @creator = AttendanceCreator.new(
      event: @event, search_param: params[:search_param]
    )
    if @creator.call
      redirect_to event_path(@event),
                  notice: "Successfully checked in
                  #{@creator.attendance.first_name}
                  #{@creator.attendance.last_name}!"
    else
      redirect_to event_path(@event),
                  alert: 'Check-in failed'
    end
  end

  def index
    @attendances = @event.attendances
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    if @attendance.destroy
      redirect_to event_attendances_path(@event),
                  notice: 'Successfully deleted attendance!'
    else
      redirect_to event_attendances_path(@event),
                  alert: 'Failed to delete attendance'
    end
  end

  def export
    @attendances = @event.attendances
    generator = CsvGenerator.new(data: @attendances)
    if generator.generate
      send_data(generator.csv, filename: csv_filename, type: 'text/csv')
    else
      flash_alerts(generator)
      render 'index'
    end
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def csv_filename
    time_str = Time.zone.today.to_s(:number)
    event_name = @event.title.parameterize.underscore[0..15]
    "#{event_name}_export_#{time_str}.csv"
  end

  def attendance_params
    params.require(:attendance).permit(:search_param)
  end

  def authorize!
    authorize(Attendance.new(event: @event))
  end
end

app/views/attendances/index.html.erb
<div class="container">
  <br />
  <div class="text-center">
    <h1>Attendee List: <%= @event.title %></h1>
  </div>

  <div class="container">
    <div class='btn-group' role='group'>
      <%= button_to 'Event Check-In', event_path(@event), method: :get, :class => 'btn btn-yale mr-1' %>
      <%= button_to 'Export CSV', export_event_attendances_path(@event), method: :get, :class => 'btn btn-primary mr-1' %>
      <%= button_to 'Edit Event', edit_event_path(@event), method: :get, :class => 'btn btn-primary mr-1' %>
    </div>
  </div>

  <div class="container">
    <table aria-label="Attendee List" class="table-borderless mb-3" tabindex="0">
      <caption style="caption-side: top; text-align: right;">
        <%= @event.attendances.size %> Recorded
      </caption>
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">NetID</th>
          <th scope="col">Email</th>
          <th scope="col">Check-in Time</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @event.attendances.each do |attendance| %>
          <tr>
            <td data-role="attendance.first-name"><%= attendance.first_name.titleize %></td>
            <td data-role="attendance.last-name"><%= attendance.last_name.titleize %></td>
            <td data-role="attendance.net-id"><%= attendance.net_id %></td>
            <td data-role="attendance.email"><%= attendance.email.downcase %></td>
            <td data-role="attendance.check-in"><%= attendance.checked_in_at.strftime('%Y-%m-%d %I:%M %p') %></td>
            <td data-role="delete attendance">
              <%= button_to 'X', event_attendance_path(attendance.event.id, attendance.id), method: :delete, data: { confirm: 'Are you sure? This action cannot be undone.'}, :class => 'btn btn-danger btn-sm', aria: { label: 'Delete Attendance' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>